version: '3'

networks:
  shipboard:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_shipboard
    ports:
      - "8082:80"
    volumes:
      - ./shipboard:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - shipboard

  mysql:
    image: mysql:5.7.29
    command: mysqld --sql_mode=""
    container_name: mysql_shipboard
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: shipboard
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - shipboard

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_shipboard
    volumes:
      - ./shipboard:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - shipboard

  composer:
    image: composer:latest
    container_name: composer_shipboard
    volumes:
      - ./shipboard:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - shipboard

  npm:
    image: node:13.7
    container_name: npm_shipboard
    volumes:
      - ./shipboard:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_shipboard
    volumes:
      - ./shipboard:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - shipboard
